### PR TITLE
fix and update layout information

### PR DESCRIPTION
**Pull request by DaYePython**
fix arguments in toCollect function:
toFind(btn, c_btn_depth, "", c_btn_indexInParent, true).findOne().click();

layout change:

1. var c_depth = 11;
2. var c_btn_depth = 18;

### CODE REVIEW

**Comment by Rukawalee** [comment]
> fix arguments in toCollect function:
> toFind(btn, c_btn_depth, "", c_btn_indexInParent, true).findOne().click();
> 
> layout change:
> 
> 1. var c_depth = 11;
> 2. var c_btn_depth = 18;

It's updted to custom. Could you describe accurately about that fixs arguments in toCollect function.

**Comment by DaYePython** [comment]
It's on line 149 of the tocollect function
your code
`toFind(btn, 14, "", 5, true).findOne().click();` 
If you modify the values of ` c_btn_depth` and `c_btn_indexInParent`, tocollect will report an error
you could want to code
`toFind(btn, c_btn_depth, "", c_btn_indexInParent, true).findOne().click();`

**Comment by DaYePython** [comment]
I suggest you set up a dev branch to integrate some more radical settings into the project.

**Comment by Rukawalee** [comment]
> I suggest you set up a dev branch to integrate some more radical settings into the project.

That is a good idea. Do my best to do it. Thanks.

**Comment by Rukawalee** [comment]
> It's on line 149 of the tocollect function
> your code
> `toFind(btn, 14, "", 5, true).findOne().click();`
> If you modify the values of ` c_btn_depth` and `c_btn_indexInParent`, toCollect function will report an error
> you could want to code
> `toFind(btn, c_btn_depth, "", c_btn_indexInParent, true).findOne().click();`

You are right. I got it.

**Pull request closed without merging**
